// <auto-generated />
using System;
using BedTrack.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BedTrack.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806145048_AddAuditLogColumns")]
    partial class AddAuditLogColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BedTrack.Domain.Entities.Cama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.ToTable("Camas");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("PisoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PisoId");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.HistorialCama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("CamaId")
                        .HasColumnType("integer");

                    b.Property<int>("CamaNumero")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<int>("HabitacionNumero")
                        .HasColumnType("integer");

                    b.Property<int?>("NosocomioId")
                        .HasColumnType("integer");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("HistorialCamas");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Nosocomio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Nosocomios");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("DiasInternacion")
                        .HasColumnType("integer");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Piso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Pisos");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NosocomioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NosocomioId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.UsuarioStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("NosocomioId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NosocomioId");

                    b.HasIndex("SucursalId");

                    b.ToTable("UsuariosStaff");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Cama", b =>
                {
                    b.HasOne("BedTrack.Domain.Entities.Habitacion", "Habitacion")
                        .WithMany("Camas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BedTrack.Domain.Entities.Paciente", "Paciente")
                        .WithOne("Cama")
                        .HasForeignKey("BedTrack.Domain.Entities.Cama", "PacienteId");

                    b.Navigation("Habitacion");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Habitacion", b =>
                {
                    b.HasOne("BedTrack.Domain.Entities.Piso", "Piso")
                        .WithMany("Habitaciones")
                        .HasForeignKey("PisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Piso");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Piso", b =>
                {
                    b.HasOne("BedTrack.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany("Pisos")
                        .HasForeignKey("SucursalId");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Sucursal", b =>
                {
                    b.HasOne("BedTrack.Domain.Entities.Nosocomio", "Nosocomio")
                        .WithMany("Sucursales")
                        .HasForeignKey("NosocomioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nosocomio");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.UsuarioStaff", b =>
                {
                    b.HasOne("BedTrack.Domain.Entities.Nosocomio", "Nosocomio")
                        .WithMany()
                        .HasForeignKey("NosocomioId");

                    b.HasOne("BedTrack.Domain.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId");

                    b.Navigation("Nosocomio");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Habitacion", b =>
                {
                    b.Navigation("Camas");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Nosocomio", b =>
                {
                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Cama");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Piso", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("BedTrack.Domain.Entities.Sucursal", b =>
                {
                    b.Navigation("Pisos");
                });
#pragma warning restore 612, 618
        }
    }
}
